### ISSUE TITLE
annotations/2018_MLBS_3_542000_4136000_image.xml not readable 

### ISSUE THREAD

**Issue by beerys** [weecology/NeonTreeEvaluation#31]
I'm using xml_to_annotations() from DeepForest/deepforest/utilities.py to convert all files in NeonTreeEvaluation/annotations to csv format

All files run just fine except annotations/2018_MLBS_3_542000_4136000_image.xml

I get the following error, which suggests to me that the format doesn't match what is expected:

Exception: error 'object' for path /cns/iz-d/home/vale-project/n=12.8/ttl=18262d/datasets/sbeery/NeonTreeEvaluation/annotations/2018_MLBS_3_542000_4136000_image.xml with doc annotationOrderedDict([('folder', 'crops'), ('filename', '2018_MLBS_3_542000_4136000_image.tif'), ('size', OrderedDict([('width', '10000'), ('height', '10000'), ('depth', '3')])), ('segmented', '0')])

**Comment by bw4sz** [comment]
File was empty and did not include annotations. Deleted.
